yarnPath: .yarn/releases/yarn-4.12.0.cjs
packageExtensions:
  "@cmfcmf/docusaurus-search-local@*":
    dependencies:
      "@docusaurus/utils-validation": "*"
      "@docusaurus/theme-common": "*"
  "@docusaurus/theme-mermaid@*":
    peerDependencies:
      "@docusaurus/plugin-content-docs": "*"
      react: "*"
      react-dom: "*"
